### ISSUE TITLE
Occasional crashes when long pressing backpress/delete

### ISSUE THREAD

**Issue by msasikanth** [saket/WYSIWYG#2]
Hello,

I cannot reproduce the issue every time, but occasionally app would crash when I long press the backpress/delete button.

Here is the crashlog:

> 
    java.lang.IndexOutOfBoundsException: setSpan (25 ... 36) ends beyond length 35
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
        at me.saket.markdownrenderer.MarkdownHintsSpanWriter.writeTo(MarkdownHintsSpanWriter.kt:20)
        at me.saket.markdownrenderer.MarkdownHints$textWatcher$1$1$1$1.invoke(MarkdownHints.kt:48)
        at me.saket.markdownrenderer.MarkdownHints$textWatcher$1$1$1$1.invoke(MarkdownHints.kt:18)
        at me.saket.markdownrenderer.util.ViewExtensionsKt.suspendTextWatcherAndRun(ViewExtensions.kt:8)
        at me.saket.markdownrenderer.MarkdownHints$textWatcher$1$1$1.run(MarkdownHints.kt:46)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
>

**Comment by saket** [comment]
Hrm, I think I know what's causing this. I'll try reproducing this. What device were you testing this on @msasikanth?

**Comment by msasikanth** [comment]
I am testing it on Pixel 3 with Q beta

**Comment by saket** [comment]
Hey @msasikanth, I haven't gotten a chance to look at this yet, but I made an improvement to the parser in https://github.com/saket/WYSIWYG/commit/4b98822bc68dc0acf22999113302c69e9cb6cb50 and was wondering if it fixes this issue. Could you please test again?

**Comment by msasikanth** [comment]
Hey @saket , The issues seem to be resolved now. Thanks for fixing it 👍🏼, You can close the issue now

**Comment by saket** [comment]
Awesome, thanks @msasikanth!

**Comment by msasikanth** [comment]
When can I expect a maven link to library? 😅

**Comment by saket** [comment]
Soon! I'm speaking at ChicagoRoboto about this library (and a few other stuff I built for Dank) and I'm barely able to find time outside its preparation. I plan to do upload this to maven and write a introduction blog post once that's over.

Till then, please use jitpack.io?
